version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    depends_on:
      - db
  
  bot:
    container_name: bot
    build:
      context: ./bot
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    volumes:
      - ./bot:/bot
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  redis:
    container_name: redis
    image: redis:latest
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis-data
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:16.2
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  redis-data:
  pgdata:   