version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - .env
  
  bot:
    container_name: bot
    build:
      context: ./bot
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    volumes:
      - ./bot:/bot
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  redis:
    container_name: redis
    image: redis:latest
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis-data
    restart: unless-stopped

volumes:
  redis-data:
      