version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/ssl/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --force-renewal --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}
    depends_on:
      - nginx
